### ISSUE TITLE
Interesting, how did you managed to plug GitHub issues into the dev.to platform

### ISSUE THREAD

**Issue by svetlyak40wt** [onmyway133/blog#163]
I've found your post https://dev.to/onmyway133/changing-electron-app-icon and fist thought there is some static site generator which uses GitHub's issues as a datasource.

Am I right?

**Comment by onmyway133** [comment]
@svetlyak40wt Hi, it can be pretty easy to write such script, but in my case I just copy paste since both uses Markdown 😛
