### ISSUE TITLE
Links for tools

### ISSUE THREAD

**Issue by onmyway133** [onmyway133/blog#509]
## Xcode

- [Engineering best practices](https://learntalks.com/Pragma-Mark/2019/Pragma-Mark-2019-Pragma-Conference-2019-Mattt-Engineering-best-practices-mi-fan-un-baffo!/)
- https://fbflipper.com/
- https://www.wtfautolayout.com/
- https://quicktype.io/
- https://github.com/woshiccm/Pecker
- https://github.com/rockbruno/SwiftInfo
- https://github.com/IBDecodable/IBLinter
- https://github.com/ChargePoint/xcparse

## Terminal

- https://github.com/ggreer/the_silver_searcher
- https://github.com/nodenv/nodenv
- https://github.com/rbenv/rbenv
- https://github.com/pyenv/pyenv
- https://ohmyz.sh/
- https://brew.sh/

## Apps

- https://sherlock.inspiredcode.io/
- https://www.mowglii.com/itsycal/
- https://github.com/eczarny/spectacle
- https://www.sublimemerge.com/

**Comment by chosa91** [comment]
xcassestslint isn't available 😢
