### ISSUE TITLE
Push notification crashed

### ISSUE THREAD

**Issue by MaPoLom** [onmyway133/blog#637]
Hi,

Cannot start the Push Notificaitons app on my Mac anymore, it crashes directly.

Copy from log:
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Can you help out?

**Comment by onmyway133** [comment]
@MaPoLom Hi please submit issue in PushNotifications repo
